export const languageOptions = [
  {
    name: "javascript",
    version: "18.15.0",
    aliases: ["node-javascript", "node-js", "javascript", "js"],
    runtime: "node",
  },
  {
    name: "cpp",
    version: "10.2.0",
    aliases: ["cpp", "g++"],
    runtime: "gcc",
  },
  {
    name: "c",
    version: "10.2.0",
    aliases: ["gcc"],
    runtime: "gcc",
  },
  {
    name: "python2",
    version: "2.7.18",
    aliases: ["py2", "python2"],
  },
  {
    name: "python",
    version: "3.10.0",
    aliases: ["py", "py3", "python3", "python3.10"],
  },
  {
    name: "bash",
    version: "5.2.0",
    aliases: ["sh"],
  },
  {
    name: "befunge93",
    version: "0.2.0",
    aliases: ["b93"],
  },
  {
    name: "bqn",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "brachylog",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "brainfuck",
    version: "2.7.3",
    aliases: ["bf"],
  },
  {
    name: "cjam",
    version: "0.6.5",
    aliases: [],
  },
  {
    name: "clojure",
    version: "1.10.3",
    aliases: ["clojure", "clj"],
  },
  {
    name: "cobol",
    version: "3.1.2",
    aliases: ["cob"],
  },
  {
    name: "coffeescript",
    version: "2.5.1",
    aliases: ["coffeescript", "coffee"],
  },
  {
    name: "cow",
    version: "1.0.0",
    aliases: ["cow"],
  },
  {
    name: "crystal",
    version: "0.36.1",
    aliases: ["crystal", "cr"],
  },
  {
    name: "dart",
    version: "2.19.6",
    aliases: [],
  },
  {
    name: "dash",
    version: "0.5.11",
    aliases: ["dash"],
  },
  {
    name: "typescript",
    version: "1.32.3",
    aliases: ["deno", "deno-ts"],
    runtime: "deno",
  },
  {
    name: "javascript",
    version: "1.32.3",
    aliases: ["deno-js"],
    runtime: "deno",
  },
  {
    name: "basic.net",
    version: "5.0.201",
    aliases: [
      "basic",
      "visual-basic",
      "visual-basic.net",
      "vb",
      "vb.net",
      "vb-dotnet",
      "dotnet-vb",
      "basic-dotnet",
      "dotnet-basic",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsharp.net",
    version: "5.0.201",
    aliases: [
      "fsharp",
      "fs",
      "f#",
      "fs.net",
      "f#.net",
      "fsharp-dotnet",
      "fs-dotnet",
      "f#-dotnet",
      "dotnet-fsharp",
      "dotnet-fs",
      "dotnet-fs",
    ],
    runtime: "dotnet",
  },
  {
    name: "csharp.net",
    version: "5.0.201",
    aliases: [
      "csharp",
      "c#",
      "cs",
      "c#.net",
      "cs.net",
      "c#-dotnet",
      "cs-dotnet",
      "csharp-dotnet",
      "dotnet-c#",
      "dotnet-cs",
      "dotnet-csharp",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsi",
    version: "5.0.201",
    aliases: [
      "fsx",
      "fsharp-interactive",
      "f#-interactive",
      "dotnet-fsi",
      "fsi-dotnet",
      "fsi.net",
    ],
    runtime: "dotnet",
  },
  {
    name: "dragon",
    version: "1.9.8",
    aliases: [],
  },
  {
    name: "elixir",
    version: "1.11.3",
    aliases: ["elixir", "exs"],
  },
  {
    name: "emacs",
    version: "27.1.0",
    aliases: ["emacs", "el", "elisp"],
  },
  {
    name: "emojicode",
    version: "1.0.2",
    aliases: ["emojic"],
  },
  {
    name: "erlang",
    version: "23.0.0",
    aliases: ["erlang", "erl", "escript"],
  },
  {
    name: "file",
    version: "0.0.1",
    aliases: ["executable", "elf", "binary"],
  },
  {
    name: "forte",
    version: "1.0.0",
    aliases: ["forter"],
  },
  {
    name: "forth",
    version: "0.7.3",
    aliases: ["gforth"],
  },
  {
    name: "freebasic",
    version: "1.9.0",
    aliases: ["bas", "fbc", "basic", "qbasic", "quickbasic"],
  },
  {
    name: "awk",
    version: "5.1.0",
    aliases: ["gawk"],
    runtime: "gawk",
  },
  {
    name: "d",
    version: "10.2.0",
    aliases: ["gdc"],
    runtime: "gcc",
  },
  {
    name: "fortran",
    version: "10.2.0",
    aliases: ["fortran", "f90"],
    runtime: "gcc",
  },
  {
    name: "go",
    version: "1.16.2",
    aliases: ["go", "golang"],
  },
  {
    name: "golfscript",
    version: "1.0.0",
    aliases: ["golfscript"],
  },
  {
    name: "groovy",
    version: "3.0.7",
    aliases: ["groovy", "gvy"],
  },
  {
    name: "haskell",
    version: "9.0.1",
    aliases: ["haskell", "hs"],
  },
  {
    name: "husk",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "iverilog",
    version: "11.0.0",
    aliases: ["verilog", "vvp"],
  },
  {
    name: "japt",
    version: "2.0.0",
    aliases: ["japt"],
  },
  {
    name: "java",
    version: "15.0.2",
    aliases: [],
  },
  {
    name: "jelly",
    version: "0.1.31",
    aliases: [],
  },
  {
    name: "julia",
    version: "1.8.5",
    aliases: ["jl"],
  },
  {
    name: "kotlin",
    version: "1.8.20",
    aliases: ["kt"],
  },
  {
    name: "lisp",
    version: "2.1.2",
    aliases: ["lisp", "cl", "sbcl", "commonlisp"],
  },
  {
    name: "llvm_ir",
    version: "12.0.1",
    aliases: ["llvm", "llvm-ir", "ll"],
  },
  {
    name: "lolcode",
    version: "0.11.2",
    aliases: ["lol", "lci"],
  },
  {
    name: "lua",
    version: "5.4.4",
    aliases: [],
  },
  {
    name: "csharp",
    version: "6.12.0",
    aliases: ["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"],
    runtime: "mono",
  },
  {
    name: "basic",
    version: "6.12.0",
    aliases: ["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"],
    runtime: "mono",
  },
  {
    name: "nasm",
    version: "2.15.5",
    aliases: ["asm", "nasm32"],
    runtime: "nasm",
  },
  {
    name: "nasm64",
    version: "2.15.5",
    aliases: ["asm64"],
    runtime: "nasm",
  },
  {
    name: "nim",
    version: "1.6.2",
    aliases: [],
  },
  {
    name: "ocaml",
    version: "4.12.0",
    aliases: ["ocaml", "ml"],
  },
  {
    name: "octave",
    version: "8.1.0",
    aliases: ["matlab", "m"],
  },
  {
    name: "osabie",
    version: "1.0.1",
    aliases: ["osabie", "05AB1E", "usable"],
  },
  {
    name: "paradoc",
    version: "0.6.0",
    aliases: ["paradoc"],
  },
  {
    name: "pascal",
    version: "3.2.2",
    aliases: ["freepascal", "pp", "pas"],
  },
  {
    name: "perl",
    version: "5.36.0",
    aliases: ["pl"],
  },
  {
    name: "php",
    version: "8.2.3",
    aliases: [],
  },
  {
    name: "ponylang",
    version: "0.39.0",
    aliases: ["pony", "ponyc"],
  },
  {
    name: "prolog",
    version: "8.2.4",
    aliases: ["prolog", "plg"],
  },
  {
    name: "pure",
    version: "0.68.0",
    aliases: [],
  },
  {
    name: "powershell",
    version: "7.1.4",
    aliases: ["ps", "pwsh", "ps1"],
    runtime: "pwsh",
  },
  {
    name: "pyth",
    version: "1.0.0",
    aliases: ["pyth"],
  },

  {
    name: "racket",
    version: "8.3.0",
    aliases: ["rkt"],
  },
  {
    name: "raku",
    version: "6.100.0",
    aliases: ["raku", "rakudo", "perl6", "p6", "pl6"],
  },
  {
    name: "retina",
    version: "1.2.0",
    aliases: ["ret"],
  },
  {
    name: "rockstar",
    version: "1.0.0",
    aliases: ["rock", "rocky"],
  },
  {
    name: "rscript",
    version: "4.1.1",
    aliases: ["r"],
  },
  {
    name: "ruby",
    version: "3.0.1",
    aliases: ["ruby3", "rb"],
  },
  {
    name: "rust",
    version: "1.68.2",
    aliases: ["rs"],
  },
  {
    name: "samarium",
    version: "0.3.1",
    aliases: ["sm"],
  },
  {
    name: "scala",
    version: "3.2.2",
    aliases: ["sc"],
  },
  {
    name: "smalltalk",
    version: "3.2.3",
    aliases: ["st"],
  },
  {
    name: "sqlite3",
    version: "3.36.0",
    aliases: ["sqlite", "sql"],
  },
  {
    name: "swift",
    version: "5.3.3",
    aliases: ["swift"],
  },
  {
    name: "vlang",
    version: "0.3.3",
    aliases: ["v"],
  },
  {
    name: "vyxal",
    version: "2.4.1",
    aliases: [],
  },
  {
    name: "yeethon",
    version: "3.10.0",
    aliases: ["yeethon3"],
  },
  {
    name: "zig",
    version: "0.10.1",
    aliases: [],
  },
  {
    name: "typescript",
    version: "5.0.3",
    aliases: ["ts", "node-ts", "tsc", "typescript5", "ts5"],
  },
];

export const CODE_SNIPPETS = {
  javascript: `\nfunction greet(name) {\n\tconsole.log("Hello, " + name + "!");\n}\n\ngreet("Alex");\n`,
  typescript: `\ntype Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello, " + data.name + "!");\n}\n\ngreet({ name: "Alex" });\n`,
  python: `\ndef greet(name):\n\tprint("Hello, " + name + "!")\n\ngreet("Alex")\n`,
  java: `\npublic class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello World");\n\t}\n}\n`,
  csharp:
    'using System;\n\nnamespace HelloWorld\n{\n\tclass Hello { \n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine("Hello World in C#");\n\t\t}\n\t}\n}\n',
  php: "<?php\n\n$name = 'Alex';\necho $name;\n",
  cpp: '#include<bits/stdc++.h>\nusing namespace std;\nint main()\n{\n\tcout << "Hello World" << endl;\n\treturn 0;\n}',
};
