export const languageOptions = [
  {
    value: "javascript",
    name: "JavaScript (Node.js 18.15.0)",
    version: "18.15.0",
    aliases: ["node-javascript", "node-js", "javascript", "js"],
    runtime: "node",
  },
  {
    value: "javascript",
    name: "JavaScript (Deno.js 1.32.3)",
    version: "1.32.3",
    aliases: ["deno-js"],
    runtime: "deno",
  },
  {
    value: "typescript",
    name: "TypeScript (Node.js 5.0.3)",
    version: "5.0.3",
    aliases: ["ts", "node-ts", "tsc", "typescript5", "ts5"],
  },

  {
    value: "cpp",
    name: "C++ (GCC 10.2.0)",
    version: "10.2.0",
    aliases: ["cpp", "g++"],
    runtime: "gcc",
  },
  {
    value: "c",
    name: "C (GCC 10.2.0)",
    version: "10.2.0",
    aliases: ["gcc"],
    runtime: "gcc",
  },
  {
    value: "python",
    name: "Python (3.10.0)",
    version: "3.10.0",
    aliases: ["py", "py3", "python3", "python3.10"],
  },
  {
    value: "python2",
    name: "Python (2.7.18)",
    version: "2.7.18",
    aliases: ["py2", "python2"],
  },

  {
    value: "bash",
    name: "Bash (5.2.0)",
    version: "5.2.0",
    aliases: ["sh"],
  },
  {
    value: "clojure",
    name: "Clojure (1.10.3)",
    version: "1.10.3",
    aliases: ["clojure", "clj"],
  },
  {
    value: "cobol",
    name: "COBOL (GnuCOBOL 3.1.2)",
    version: "3.1.2",
    aliases: ["cob"],
  },

  {
    value: "basic.net",
    name: "Visual Basic.Net (vbnc 5.0.201)",
    version: "5.0.201",
    aliases: [
      "basic",
      "visual-basic",
      "visual-basic.net",
      "vb",
      "vb.net",
      "vb-dotnet",
      "dotnet-vb",
      "basic-dotnet",
      "dotnet-basic",
    ],
    runtime: "dotnet",
  },
  {
    value: "fsharp.net",
    name: "F# (.NET Core SDK 5.0.201)",
    version: "5.0.201",
    aliases: [
      "fsharp",
      "fs",
      "f#",
      "fs.net",
      "f#.net",
      "fsharp-dotnet",
      "fs-dotnet",
      "f#-dotnet",
      "dotnet-fsharp",
      "dotnet-fs",
      "dotnet-fs",
    ],
    runtime: "dotnet",
  },
  {
    value: "csharp.net",
    name: "C# (.NET 5.0.201)",
    version: "5.0.201",
    aliases: [
      "csharp",
      "c#",
      "cs",
      "c#.net",
      "cs.net",
      "c#-dotnet",
      "cs-dotnet",
      "csharp-dotnet",
      "dotnet-c#",
      "dotnet-cs",
      "dotnet-csharp",
    ],
    runtime: "dotnet",
  },

  {
    value: "elixir",
    name: "Elixir (1.11.3)",
    version: "1.11.3",
    aliases: ["elixir", "exs"],
  },
  {
    value: "erlang",
    name: "Erlang (OTP 23.0.0)",
    version: "23.0.0",
    aliases: ["erlang", "erl", "escript"],
  },
  {
    value: "forte",
    name: "Forte (1.0.0)",
    version: "1.0.0",
    aliases: ["forter"],
  },
  {
    value: "forth",
    name: "Forth (0.7.3)",
    version: "0.7.3",
    aliases: ["gforth"],
  },

  {
    value: "d",
    name: "D (GCC 10.2.0)",
    version: "10.2.0",
    aliases: ["gdc"],
    runtime: "gcc",
  },
  {
    value: "fortran",
    name: "Fortran (GCC 10.2.0)",
    version: "10.2.0",
    aliases: ["fortran", "f90"],
    runtime: "gcc",
  },
  {
    value: "go",
    name: "Go (1.16.2)",
    version: "1.16.2",
    aliases: ["go", "golang"],
  },

  {
    value: "groovy",
    name: "Groovy (3.0.7)",
    version: "3.0.7",
    aliases: ["groovy", "gvy"],
  },
  {
    value: "haskell",
    name: "Haskell (GHC 9.0.1)",
    version: "9.0.1",
    aliases: ["haskell", "hs"],
  },
  {
    value: "husk",
    name: "Husk (1.0.0)",
    version: "1.0.0",
    aliases: [],
  },

  {
    value: "java",
    name: "Java (OpenJDK 15.0.2)",
    version: "15.0.2",
    aliases: [],
  },
  {
    value: "kotlin",
    name: "Kotlin (1.8.20)",
    version: "1.8.20",
    aliases: ["kt"],
  },
  {
    value: "lisp",
    name: "Common Lisp (SBCL 2.1.2)",
    version: "2.1.2",
    aliases: ["lisp", "cl", "sbcl", "commonlisp"],
  },

  {
    value: "lolcode",
    name: "LOLCODE (0.11.2)",
    version: "0.11.2",
    aliases: ["lol", "lci"],
  },
  {
    value: "lua",
    name: "Common Lisp (SBCL 5.4.4)",
    version: "5.4.4",
    aliases: [],
  },
  {
    value: "csharp",
    name: "C# (Mono 6.12.0)",
    version: "6.12.0",
    aliases: ["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"],
    runtime: "mono",
  },
  {
    value: "basic",
    name: "Basic (FBC 6.12.0)",
    version: "6.12.0",
    aliases: ["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"],
    runtime: "mono",
  },

  {
    value: "nasm64",
    name: "Assembly (NASM 2.15.5)",
    version: "2.15.5",
    aliases: ["asm64"],
    runtime: "nasm",
  },

  {
    value: "ocaml",
    name: "OCaml (4.12.0)",
    version: "4.12.0",
    aliases: ["ocaml", "ml"],
  },
  {
    value: "octave",
    name: "Octave (8.1.0)",
    version: "8.1.0",
    aliases: ["matlab", "m"],
  },
  {
    value: "pascal",
    name: "Pascal (FPC 3.2.2)",
    version: "3.2.2",
    aliases: ["freepascal", "pp", "pas"],
  },
  {
    value: "perl",
    name: "Perl (5.36.0)",
    version: "5.36.0",
    aliases: ["pl"],
  },
  {
    value: "php",
    name: "PHP (8.2.3)",
    version: "8.2.3",
    aliases: [],
  },

  {
    value: "prolog",
    name: "Prolog (GNU Prolog 8.2.4)",
    version: "8.2.4",
    aliases: ["prolog", "plg"],
  },

  {
    value: "powershell",
    name: "Powershell (7.1.4)",
    version: "7.1.4",
    aliases: ["ps", "pwsh", "ps1"],
    runtime: "pwsh",
  },

  {
    value: "ruby",
    name: "Ruby (3.0.1)",
    version: "3.0.1",
    aliases: ["ruby3", "rb"],
  },
  {
    value: "rust",
    name: "Rust (1.68.2)",
    version: "1.68.2",
    aliases: ["rs"],
  },
  {
    value: "scala",
    name: "Scala (3.2.2)",
    version: "3.2.2",
    aliases: ["sc"],
  },
  {
    value: "sqlite3",
    name: "SQL (SQLite 3.36.0)",
    version: "3.36.0",
    aliases: ["sqlite", "sql"],
  },
  {
    value: "swift",
    name: "Swift (5.3.3)",
    version: "5.3.3",
    aliases: ["swift"],
  },
];

export const CODE_SNIPPETS = {
  javascript: `\nfunction greet(name) {\n\tconsole.log("Hello, " + name);\n}\n\ngreet("World");\n`,
  typescript: `\ntype Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello " + data.name);\n}\n\ngreet({ name: "World" });\n`,
  python: `\ndef greet(name):\n\tprint("Hello " + name)\n\ngreet("World")\n`,
  java: `\npublic class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello, World");\n\t}\n}\n`,
  csharp: `using System;\n\nnamespace HelloWorld\n{\n\tclass Hello\n\t{\n\t\tstatic void Main(string[] args)\n\t\t{\n\t\t\tConsole.WriteLine("Hello, World in C#");\n\t\t}\n\t}\n}\n`,
  php: `<?php\n\n$name = 'Alex';\necho "Hello, " . $name . "!";\n?>\n`,
  cpp: `#include<bits/stdc++.h>\nusing namespace std;\n\nint main()\n{\n\tcout << "Hello, World" << endl;\n\treturn 0;\n}\n`,
  c: `#include <stdio.h>\n\nint main() {\n\tprintf("Hello, World\\n");\n\treturn 0;\n}\n`,
  python2: `\ndef greet(name):\n\tprint "Hello " + name\n\ngreet("World")\n`,
  bash: `\necho "Hello, World"\n`,
  clojure: `\n(println "Hello, World")\n`,
  cobol: `\nIDENTIFICATION DIVISION.\nPROGRAM-ID. HelloWorld.\nPROCEDURE DIVISION.\n\tDISPLAY "Hello, World".\n\tSTOP RUN.\n`,
  "basic.net": `\nModule HelloWorld\n\tSub Main()\n\t\tConsole.WriteLine("Hello, World")\n\tEnd Sub\nEnd Module\n`,
  "fsharp.net": `\nopen System\n\n[<EntryPoint>]\nlet main argv =\n\tprintfn "Hello, World"\n\t0 // return an integer exit code\n`,
  "csharp.net": `\nusing System;\n\nnamespace HelloWorld\n{\n\tclass Program\n\t{\n\t\tstatic void Main(string[] args)\n\t\t{\n\t\t\tConsole.WriteLine("Hello, World");\n\t\t}\n\t}\n}\n`,
  elixir: `\nIO.puts "Hello, World"\n`,
  erlang: `\n-module(hello).\n-export([world/0]).\n\nworld() ->\n\tio:format("Hello, World~n").\n`,
  forte: `\n! Hello World\n`,
  forth: `\n." Hello, World"\n`,
  d: `\nimport std.stdio;\n\nvoid main() {\n\twriteln("Hello, World");\n}\n`,
  fortran: `\nprogram hello\n\tprint *, "Hello, World"\nend program hello\n`,
  go: `\npackage main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, World")\n}\n`,
  groovy: `\nprintln "Hello, World"\n`,
  haskell: `\nmain :: IO ()\nmain = putStrLn "Hello, World"\n`,
  husk: `\n"Hello, World"↵\n`,
  kotlin: `\nfun main() {\n\tprintln("Hello, World")\n}\n`,
  lisp: `\n(format t "Hello, World~%")\n`,
  lolcode: `\nHAI 1.2\n\nI HAS A NAME ITZ "World"\n\nVISIBLE "Hello, " + NAME\nKTHXBYE\n`,
  lua: `\nprint("Hello, World")\n`,
  nasm64: `\nsection .data\n\tmsg db 'Hello, World',0\n\nsection .text\n\tglobal _start\n\n_start:\n\tmov rax, 1\n\tmov rdi, 1\n\tmov rsi, msg\n\tmov rdx, 13\n\tsyscall\n\n\tmov rax, 60\n\txor rdi, rdi\n\tsyscall\n`,
  ocaml: `\nprint_endline "Hello, World";;\n`,
  octave: `\ndisp('Hello, World');\n`,
  pascal: `\nprogram Hello;\nbegin\n\twriteln('Hello, World');\nend.\n`,
  perl: `\nprint "Hello, World\\n";\n`,
  php: `<?php\n\necho "Hello, World";\n?>\n`,
  prolog: `\n:- initialization(main).\n\nmain :-\n\twrite('Hello, World'), nl, halt.\n`,
  powershell: `\nWrite-Output "Hello, World"\n`,
  ruby: `\nputs "Hello, World"\n`,
  rust: `\nfn main() {\n\tprintln!("Hello, World");\n}\n`,
  scala: `\nobject HelloWorld {\n\tdef main(args: Array[String]): Unit = {\n\t\tprintln("Hello, World")\n\t}\n}\n`,
  sqlite3: `\nSELECT 'Hello, World';\n`,
  swift: `\nprint("Hello, World")\n`,
};
